name: Deploy to AWS S3 & CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      NEXT_PUBLIC_NOTION_PAGE_ID: ${{ secrets.NOTION_PAGE_ID }}
      NEXT_PUBLIC_ACTIVE_NOTION_USER_ID: ${{ secrets.ACTIVE_NOTION_USER_ID }}
      NEXT_PUBLIC_NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm & Node
        uses: ./.github/actions/pnpm-setup-node

      - name: Install Dependencies
        run: pnpm install

      - name: Build Next.js & Export Static Files
        run: pnpm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sync Static Files to S3
        run: aws s3 sync ./out s3://${{ vars.AWS_S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
